assets: /app/libero/libero/libero/assets
bddl_files: /app/libero/libero/libero/bddl_files
benchmark_root: /app/libero/libero/libero
datasets: /app/libero/libero/datasets
init_states: /app/libero/libero/libero/init_files
